spring:
  application:
    name: flux  #·þÎñÃû³Æ
  datasource:
    url: jdbc:mysql://localhost:3306/excel?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource